apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-tx
spec:
  replicas: 0
  selector:
    matchLabels:
      app: financial-tx
  template:
    metadata:
      labels:
        app: financial-tx
    spec:
      containers:
        - name: app
          image: fin-serv:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "10m"       # 極低請求，確保能跑
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          env:
            - name: APP_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_PORT
              value: "3306"
            # 同時給兩個名稱，確保 Spring 一定吃得到
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "host.docker.internal:29092"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "host.docker.internal:29092"

            - name: MONGODB_HOST
              value: "host.docker.internal"
            - name: MONGODB_PORT
              value: "27017" # 確保這是你 Mongo 在 Docker Compose 開的 Port
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
      terminationGracePeriodSeconds: 30